spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_CHAT_BASE_URL:https://llm.waha.ai/qwen3-30b-thinking}
      #      base-url: ${OPENAI_CHAT_BASE_URL:http://llm.waha.ai/qwen3-30b-insturct}
      chat:
        options:
          model: Qwen/Qwen3-30B-A3B-Thinking-2507
  #          model: Qwen/Qwen3-30B-A3B-Instruct-2507
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_DEFAULT_SCHEMA:public}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

gitlab:
  url: ${GITLAB_URL}
  token: ${GITLAB_TOKEN}
server:
  servlet:
    context-path: /r100/git-helper